# Generated by Django 4.2.4 on 2023-08-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_follow_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
